package com.kseltouch.launcher;

import android.content.Context;
import android.content.SharedPreferences;
import android.media.AudioManager;
import android.media.SoundPool;
import android.os.Build;
import android.os.Vibrator;
import android.preference.PreferenceManager;
import android.util.Log;

/**
 * Short UI sounds via SoundPool (low latency, preloaded).
 * Choice STREAM_MUSIC (not STREAM_SYSTEM): SYSTEM stream is not
 * volume-controllable by the user on many devices and is muted/restricted
 * on newer Android; MUSIC respects user volume and silent mode, and
 * ticks are UI feedback, not system alerts.
 * Silent/vibrate mode -&gt; no sounds. Vibration optional 12ms on launch.
 *
 * res/raw files (wav, generated by tools/gen_sounds.py + tools/GenSounds.java):
 *   nav_move, nav_select, nav_back, menu_open, launch_whoosh, snd_error, startup
 */
public class KselSound {
    private static final String TAG = "KselSound";

    public int sMove = 0, sSelect = 0, sBack = 0, sOpen = 0, sWhoosh = 0, sError = 0, sStartup = 0;
    private SoundPool pool;
    private AudioManager am;
    private Vibrator vib;
    private Context ctx;
    private long lastTick = 0;
    private boolean prefNav = true;
    private boolean prefVib = true;

    public KselSound(Context c) {
        ctx = c.getApplicationContext();
        am = (AudioManager) ctx.getSystemService(Context.AUDIO_SERVICE);
        try {
            vib = (Vibrator) ctx.getSystemService(Context.VIBRATOR_SERVICE);
        } catch (Exception e) {
            vib = null;
        }
        ensurePool();
    }

    private void ensurePool() {
        if (pool != null) return;
        try {
            pool = new SoundPool(8, AudioManager.STREAM_MUSIC, 0);
        } catch (Exception e) {
            Log.w(TAG, "SoundPool: " + e);
            pool = null;
        }
    }

    /** Called by the view whenever settings change: no SharedPreferences reads per sound. */
    public void reloadPrefs() {
        try {
            SharedPreferences p = PreferenceManager.getDefaultSharedPreferences(ctx);
            prefNav = p.getBoolean("snd_nav", true);
            prefVib = p.getBoolean("vib_launch", true);
        } catch (Exception e) {
            // keep previous values
        }
    }

    public void preload() {
        ensurePool(); // pool is released on detach; re-create it when the view comes back
        if (pool == null) return;
        // Load on caller thread (already background from Launcher); ids 0 if missing.
        sMove = load("nav_move");
        sSelect = load("nav_select");
        sBack = load("nav_back");
        sOpen = load("menu_open");
        sWhoosh = load("launch_whoosh");
        sError = load("snd_error");
        sStartup = load("startup");
    }

    private int load(String name) {
        try {
            int id = ctx.getResources().getIdentifier(name, "raw", ctx.getPackageName());
            if (id == 0) return 0;
            return pool.load(ctx, id, 1);
        } catch (Exception e) {
            return 0;
        }
    }

    private boolean enabled() {
        if (!prefNav) return false;
        try {
            int mode = am.getRingerMode();
            if (mode != AudioManager.RINGER_MODE_NORMAL) return false;
        } catch (Exception e) {
            // ignore
        }
        return true;
    }

    private float vol() {
        try {
            int cur = am.getStreamVolume(AudioManager.STREAM_MUSIC);
            int max = am.getStreamMaxVolume(AudioManager.STREAM_MUSIC);
            if (max <= 0) return 0.5f;
            float f = (float) cur / (float) max;
            if (f < 0.05f) return 0f;
            return 0.25f + 0.75f * f; // fraction of system volume
        } catch (Exception e) {
            return 0.5f;
        }
    }

    private void play(int sid, float rate) {
        if (pool == null || sid == 0) return;
        if (!enabled()) return;
        float v = vol();
        if (v <= 0f) return;
        try {
            pool.play(sid, v, v, 1, 0, rate);
        } catch (Exception e) {
            Log.w(TAG, "play: " + e);
        }
    }

    public void tick() {
        long now = android.os.SystemClock.uptimeMillis();
        if (now - lastTick < 55) return; // throttle tick frequency
        lastTick = now;
        // slight pitch variation for liveliness 0.97..1.03
        float r = 0.97f + (float) (Math.random() * 0.06f);
        play(sMove, r);
    }

    public void select() { play(sSelect, 1.0f); }
    public void back() { play(sBack, 1.0f); }
    public void open() { play(sOpen, 1.0f); }
    public void whoosh() { play(sWhoosh, 1.0f); }
    public void error() { play(sError, 1.0f); }
    public void startup() { play(sStartup, 1.0f); }

    public void vibrateLaunch() {
        try {
            if (!prefVib) return;
            if (vib == null) return;
            vib.vibrate(12);
        } catch (Exception e) {
            // ignore (no permission etc.)
        }
    }

    public void release() {
        try {
            if (pool != null) pool.release();
        } catch (Exception e) {
            // ignore
        }
        pool = null;
    }
}
